spring:
  mail:
    port: 587
    host: smtp.gmail.com
    username: ductt1531@gmail.com
    password: ryhduvjepckpjeae
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #      mail.smtp.auth: true
  #      mail.smtp.starttls.enable: true
  application:
    name: E-commerceAPI
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    username: root
    password: duc1531
    url: jdbc:mysql://localhost:3306/E-commerceAPI?createDatabaseIfNotExist=true

server:
  port: 9999

jwt.expired-time: 3600000
jwt.secret-key: duc1531

firebase-bucket: e-commerceapi-a15ef.appspot.com

#    ryhd uvje pckp jeae